# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-14 06:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0014_assignmentupload_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rejected',
            field=models.ManyToManyField(null=True, related_name='rejected', to=settings.AUTH_USER_MODEL),
        ),
    ]
